//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPTarkov.Server.Web
{
    public partial class App : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial interface IModBlazorMetadata
    {
        string? HomePage { get; init; }

        string? HomePageDescription { get; init; }

        string? WWWRootUrl { get; init; }
    }

    public partial class Routes : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public static partial class SPTWeb
    {
        public static void InitializeSptBlazor(this Microsoft.AspNetCore.Builder.WebApplicationBuilder builder, System.Collections.Generic.IReadOnlyList<Core.Models.Spt.Mod.SptMod> sptMods) { }
        public static void UseSptBlazor(this Microsoft.AspNetCore.Builder.WebApplication app) { }
    }
    public partial class _Imports
    {
        protected void Execute() { }
    }
}

namespace SPTarkov.Server.Web.Components.Auth
{
    public partial class LoginBox : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public string? FailureUrlOverride { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string? Message { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string? ReturnUrlOverride { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool ShowForm { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnParametersSet() { }
    }
}

namespace SPTarkov.Server.Web.Components.Configs
{
    public partial class ConfigJsonValueEditor : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public System.Collections.Generic.IReadOnlyDictionary<string, bool> AddableObjectPaths { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback Changed { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public int Depth { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public System.Collections.Generic.IReadOnlySet<string> IgnoredSectionPaths { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool IsRoot { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string Name { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string Path { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public System.Text.Json.Nodes.JsonNode? Value { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<System.Text.Json.Nodes.JsonNode?> ValueChanged { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnParametersSet() { }
    }

    public partial class ConfigStructuredEditor : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public System.Collections.Generic.IReadOnlyDictionary<string, bool> AddableObjectPaths { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public System.Collections.Generic.IReadOnlySet<string> IgnoredSectionPaths { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string Title { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public System.Text.Json.Nodes.JsonNode? Value { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<System.Text.Json.Nodes.JsonNode?> ValueChanged { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }
}

namespace SPTarkov.Server.Web.Components.Database
{
    public partial class DatabaseBrowserFilters : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public System.Func<string, string> GetFilterValue { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnClearFilters { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string ResultCountLabel { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string SearchText { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<string> SearchTextChanged { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Database.DatabaseTableDefinition SelectedTable { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string SelectedTableId { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<string> SelectedTableIdChanged { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public System.Func<string, string, System.Threading.Tasks.Task> SetFilterValue { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public System.Collections.Generic.IReadOnlyList<Models.Database.DatabaseTableDefinition> Tables { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class DatabaseBrowserHeader : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Database.DatabaseTableDefinition Table { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class DatabaseBrowserTable : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public System.Collections.Generic.IEnumerable<Models.Database.DatabaseRow> Rows { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Database.DatabaseRow? SelectedRow { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Database.DatabaseRow> SelectedRowChanged { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Database.DatabaseTableDefinition Table { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnParametersSet() { }
    }

    public partial class DatabaseDetailValueCard : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Database.DatabaseDetailValue Value { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class DatabaseLoadingOverlay : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public string? Error { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string ErrorTitle { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string LoadingMessage { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string LoadingTitle { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool Visible { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class DatabaseRecordDetails : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Database.DatabaseRow> OnBrowseTraderAssort { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnClose { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Database.DatabaseRow? Row { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class DatabaseRecordDetailsModal : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Database.DatabaseRow> OnBrowseTraderAssort { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnClose { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool Open { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Database.DatabaseRow? Row { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class DatabaseTraderAssortBrowser : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Database.DatabaseTraderAssort Assort { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnClose { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnParametersSet() { }
    }

    public partial class DatabaseTraderAssortModal : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Database.DatabaseTraderAssort? Assort { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool Loading { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string LoadingMessage { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnClose { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool Open { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }
}

namespace SPTarkov.Server.Web.Components.Profiles
{
    public partial class ProfileControlHeader : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public System.Collections.Generic.IReadOnlyList<Models.Profiles.ProfileSummary> Profiles { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class ProfileCreatePanel : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public string Edition { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<string> EditionChanged { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public System.Collections.Generic.IReadOnlyList<string> Editions { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool IsBusy { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnCreate { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string Username { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<string> UsernameChanged { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class ProfilePrestigePanel : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        [Microsoft.AspNetCore.Components.EditorRequired]
        public Models.Profiles.ProfileDetails Details { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool IsBusy { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Profiles.ProfilePrestigeGrantRequest> OnGrantPrestige { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnParametersSet() { }
    }

    public partial class ProfileRecordDetails : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Profiles.ProfileDetails? Details { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool IsBusy { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnClose { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Profiles.ProfilePrestigeGrantRequest> OnGrantPrestige { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Profiles.ProfileEditModel> OnSaveEdit { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnParametersSet() { }
    }

    public partial class ProfileRecordDetailsModal : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Profiles.ProfileDetails? Details { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool IsBusy { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnClose { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Profiles.ProfilePrestigeGrantRequest> OnGrantPrestige { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Profiles.ProfileEditModel> OnSaveEdit { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public bool Open { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class ProfileSelectedPanel : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public bool CanDelete { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string DeleteConfirmation { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<string> DeleteConfirmationChanged { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnDelete { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Models.Profiles.ProfileSummary? Profile { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class ProfileTable : Microsoft.AspNetCore.Components.ComponentBase
    {
        [Microsoft.AspNetCore.Components.Parameter]
        public bool IsBusy { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Profiles.ProfileSummary> OnClearMessages { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnRefresh { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Profiles.ProfileSummary> OnReloadProfile { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback OnSaveAll { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Profiles.ProfileSummary> OnSaveProfile { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public System.Collections.Generic.IReadOnlyList<Models.Profiles.ProfileSummary> Profiles { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<Models.Profiles.ProfileSummary> SelectedProfileChanged { get { throw null; } set { } }

        [Microsoft.AspNetCore.Components.Parameter]
        public string? SelectedProfileId { get { throw null; } set { } }

        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }
}

namespace SPTarkov.Server.Web.Layout
{
    public partial class BaseMainLayout : Microsoft.AspNetCore.Components.LayoutComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    public partial class BaseMudBlazorLayout : Microsoft.AspNetCore.Components.LayoutComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }
}

namespace SPTarkov.Server.Web.Models.Configs
{
    public sealed partial record ConfigEditorConfigRegistration()
    {
        public System.Func<object, System.Threading.CancellationToken, System.Threading.Tasks.ValueTask>? ApplyToRuntimeAsync { get { throw null; } init { } }
        public required string DisplayName { get { throw null; } init { } }
        public string? FileName { get { throw null; } init { } }
        public string? FilePath { get { throw null; } init { } }
        public required string Id { get { throw null; } init { } }
        public System.Collections.Generic.IReadOnlySet<string> IgnoredSectionPaths { get { throw null; } init { } }
        public System.Func<System.Threading.CancellationToken, System.Threading.Tasks.ValueTask<object?>>? LoadFromDiskAsync { get { throw null; } init { } }
        public required object RuntimeConfig { get { throw null; } init { } }
        public System.Type? RuntimeType { get { throw null; } init { } }
        public System.Func<object, System.Threading.CancellationToken, System.Threading.Tasks.ValueTask>? SaveToDiskAsync { get { throw null; } init { } }

        public static ConfigEditorConfigRegistration Create<TConfig>(string id, string displayName, TConfig runtimeConfig, string? filePath = null) { throw null; }
    }
    public sealed partial record ConfigEditorConfigSummary(string Id, string DisplayName, string FileName, Core.Models.Enums.ConfigTypes? ConfigType, System.Type RuntimeType, bool ModifiedByMods, int RuntimeCharacterCount, int CleanCharacterCount, int TopLevelPropertyCount, bool IsRegisteredConfig)
    {
    }
    public sealed partial record ConfigEditorPreset(string Id, string Name, System.Collections.Generic.IReadOnlyDictionary<string, string> ConfigJsonById, System.DateTimeOffset CreatedAt, System.DateTimeOffset UpdatedAt)
    {
    }
    public sealed partial record ConfigEditorSnapshot(ConfigEditorConfigSummary Summary, string RuntimeJson, string CleanJson, bool ModifiedByMods, System.Collections.Generic.IReadOnlyDictionary<string, bool> AddableObjectPaths, System.Collections.Generic.IReadOnlySet<string> IgnoredSectionPaths)
    {
    }
}

namespace SPTarkov.Server.Web.Models.Database
{
    public partial record DatabaseChip(string Text, MudBlazor.Color Color)
    {
    }
    public partial record DatabaseDetailSection(string Title, System.Collections.Generic.IReadOnlyList<DatabaseDetailValue> Values)
    {
    }
    public partial record DatabaseDetailValue(string Label, string Value, bool IsMono = false)
    {
    }
    public partial record DatabaseFilterOption(string Value, string Label)
    {
    }
    public partial record DatabaseProperty(string Path, string Value, string Kind)
    {
    }
    public sealed partial record DatabaseRow(string Id, string Title, string Subtitle, string Description, System.Collections.Generic.IReadOnlyDictionary<string, string> Values, System.Collections.Generic.IReadOnlyList<DatabaseDetailSection> DetailSections, System.Collections.Generic.IReadOnlyList<DatabaseChip> Chips, System.Collections.Generic.IReadOnlyList<DatabaseProperty> Properties, string PropertiesJson, string SearchText)
    {
    }
    public partial record DatabaseStat(string Label, string Value)
    {
    }
    public partial record DatabaseTableColumn(string Header, System.Func<DatabaseRow, string> GetValue, bool IsPrimary = false, bool IsMono = false)
    {
    }
    public sealed partial record DatabaseTableDefinition(string Id, string Name, string Description, string ResultLabel, string SelectionHint, System.Collections.Generic.IReadOnlyList<DatabaseTableColumn> Columns, System.Collections.Generic.IReadOnlyList<DatabaseTableFilter> Filters, System.Collections.Generic.IReadOnlyList<DatabaseStat> Stats, System.Collections.Generic.IReadOnlyList<DatabaseRow> Rows)
    {
        public static DatabaseTableDefinition Empty { get { throw null; } }
    }
    public partial record DatabaseTableFilter(string Id, string Label, string AllLabel, System.Collections.Generic.IReadOnlyList<DatabaseFilterOption> Options, System.Func<DatabaseRow, string> GetValue)
    {
    }
    public sealed partial record DatabaseTraderAssort(string TraderId, string TraderName, System.Collections.Generic.IReadOnlyList<DatabaseStat> Stats, System.Collections.Generic.IReadOnlyList<string> LoyaltyLevels, System.Collections.Generic.IReadOnlyList<DatabaseTraderAssortRow> Rows)
    {
    }
    public sealed partial record DatabaseTraderAssortRow(string Id, string TemplateId, string Name, string ShortName, string ParentId, string SlotId, string LoyaltyLevel, string LoyaltyLevelRaw, string Barter, string SearchText, System.Func<DatabaseTraderAssortRowDetails> BuildDetails)
    {
    }
    public sealed partial record DatabaseTraderAssortRowDetails(System.Collections.Generic.IReadOnlyList<DatabaseDetailSection> DetailSections, System.Collections.Generic.IReadOnlyList<DatabaseProperty> Properties, string PropertiesJson)
    {
    }
}

namespace SPTarkov.Server.Web.Models.Profiles
{
    public enum CharacterTarget
    {
        Pmc = 0,
        Scav = 1
    }

    public sealed partial record ProfileDetails(ProfileSummary Summary, ProfileEditModel EditModel, System.Collections.Generic.IReadOnlyList<Database.DatabaseDetailSection> DetailSections, System.Collections.Generic.IReadOnlyList<Database.DatabaseProperty> Properties, string PropertiesJson, ProfilePrestigeInfo PrestigeInfo)
    {
    }
    public sealed partial class ProfileEditModel
    {
        public bool HasCharacter { get { throw null; } set { } }
        public System.Collections.Generic.List<ProfileHideoutAreaEditModel> HideoutAreas { get { throw null; } set { } }
        public string Id { get { throw null; } set { } }
        public System.Collections.Generic.List<ProfileQuestOptionModel> MissingQuests { get { throw null; } set { } }
        public int? PmcExperience { get { throw null; } set { } }
        public int? PmcLevel { get { throw null; } set { } }
        public string PmcNickname { get { throw null; } set { } }
        public System.Collections.Generic.List<ProfileQuestEditModel> Quests { get { throw null; } set { } }
        public int? ScavExperience { get { throw null; } set { } }
        public int? ScavLevel { get { throw null; } set { } }
        public System.Collections.Generic.List<ProfileSkillEditModel> Skills { get { throw null; } set { } }
        public System.Collections.Generic.List<ProfileTraderEditModel> Traders { get { throw null; } set { } }
        public string Username { get { throw null; } set { } }

        public ProfileEditModel Clone() { throw null; }
    }
    public sealed partial class ProfileHideoutAreaEditModel
    {
        public bool Active { get { throw null; } set { } }
        public bool CompleteConstruction { get { throw null; } set { } }
        public int? CompleteTime { get { throw null; } set { } }
        public bool Constructing { get { throw null; } set { } }
        public string Label { get { throw null; } set { } }
        public int Level { get { throw null; } set { } }
        public int MaxLevel { get { throw null; } set { } }
        public bool PassiveBonusesEnabled { get { throw null; } set { } }
        public string Type { get { throw null; } set { } }

        public ProfileHideoutAreaEditModel Clone() { throw null; }
    }
    public sealed partial record ProfilePrestigeEditModel()
    {
        public bool Achieved { get { throw null; } set { } }
        public long AchievedAt { get { throw null; } set { } }
        public string Id { get { throw null; } set { } }
        public string Label { get { throw null; } set { } }
        public int Level { get { throw null; } set { } }
    }
    public sealed partial record ProfilePrestigeGrantRequest(string ProfileId, int TargetLevel, bool FullWipe)
    {
    }
    public sealed partial record ProfilePrestigeInfo(int CurrentLevel, int MaxLevel, System.Collections.Generic.IReadOnlyList<ProfilePrestigeEditModel> Tiers)
    {
    }
    public enum ProfileQuestEditAction
    {
        None = 0,
        AvailableForFinish = 1,
        Restart = 2
    }

    public sealed partial class ProfileQuestEditModel
    {
        public string Id { get { throw null; } set { } }
        public bool IsNew { get { throw null; } set { } }
        public string Label { get { throw null; } set { } }
        public ProfileQuestEditAction PendingAction { get { throw null; } set { } }
        public Core.Models.Enums.QuestStatusEnum Status { get { throw null; } set { } }

        public ProfileQuestEditModel Clone() { throw null; }
    }
    public sealed partial class ProfileQuestOptionModel
    {
        public string Id { get { throw null; } set { } }
        public string Label { get { throw null; } set { } }

        public ProfileQuestOptionModel Clone() { throw null; }
    }
    public sealed partial class ProfileSkillEditModel
    {
        public string Id { get { throw null; } set { } }
        public string Label { get { throw null; } set { } }
        public int Level { get { throw null; } set { } }
        public double ProgressInLevel { get { throw null; } set { } }
        public double TotalProgress { get { throw null; } }

        public ProfileSkillEditModel Clone() { throw null; }
    }
    public sealed partial record ProfileSummary(string Id, string Username, string Nickname, string Side, string Edition, int? Level, double? Experience, int ItemCount, int? ScavLevel, bool HasCharacter, bool IsInvalid, bool IsWiped, string Status)
    {
        public string LevelLabel { get { throw null; } }
    }
    public sealed partial class ProfileTraderEditModel
    {
        public string Id { get { throw null; } set { } }
        public string Label { get { throw null; } set { } }
        public int LoyaltyLevel { get { throw null; } set { } }
        public int MaxLoyaltyLevel { get { throw null; } set { } }
        public double NextResupply { get { throw null; } set { } }
        public double SalesSum { get { throw null; } set { } }
        public double Standing { get { throw null; } set { } }
        public bool Unlocked { get { throw null; } set { } }

        public ProfileTraderEditModel Clone() { throw null; }
    }
}

namespace SPTarkov.Server.Web.Pages
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/example-page")]
    public partial class ExamplePage : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }

    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/")]
    public partial class LandingPage : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnInitialized() { }
    }

    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/login")]
    public partial class LoginPage : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnParametersSet() { }
    }

    [Microsoft.AspNetCore.Authorization.Authorize(Policy = "Administrator")]
    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/profiles")]
    public partial class ProfileControlPage : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnInitialized() { }
    }

    [Microsoft.AspNetCore.Authorization.Authorize]
    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/status")]
    public partial class Status : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnInitialized() { }
    }

    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/thank-you")]
    public partial class ThankYou : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnInitialized() { }
    }

    [Microsoft.AspNetCore.Authorization.Authorize(Policy = "Administrator")]
    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/credentials")]
    public partial class UserCredentialsPage : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override System.Threading.Tasks.Task OnInitializedAsync() { throw null; }
    }
}

namespace SPTarkov.Server.Web.Pages.Configs
{
    [Microsoft.AspNetCore.Authorization.Authorize(Policy = "Administrator")]
    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/configs")]
    public partial class ConfigEditorPage : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override System.Threading.Tasks.Task OnAfterRenderAsync(bool firstRender) { throw null; }
        protected override void OnInitialized() { }
    }
}

namespace SPTarkov.Server.Web.Pages.Database
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/database")]
    public partial class DatabasePage : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override System.Threading.Tasks.Task OnAfterRenderAsync(bool firstRender) { throw null; }
        protected override void OnInitialized() { }
    }
}

namespace SPTarkov.Server.Web.Pages.Tools
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    [Microsoft.AspNetCore.Components.Layout(typeof(Layout.BaseMudBlazorLayout))]
    [Microsoft.AspNetCore.Components.Route("/tools")]
    public partial class ToolsPage : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
    }
}

namespace SPTarkov.Server.Web.Services
{
    [DI.Annotations.Injectable(DI.Annotations.InjectionType.Singleton, int.MaxValue)]
    public partial class Argon2idPasswordHasher : IPasswordHasher
    {
        public string DummyHash { get { throw null; } }

        public string Hash(string password) { throw null; }
        public bool IsEncodedHash(string value) { throw null; }
        public bool Verify(string password, string encodedHash, out bool needsRehash) { throw null; }
    }

    [DI.Annotations.Injectable(DI.Annotations.InjectionType.Singleton, int.MaxValue)]
    public partial class AuthService : Core.DI.IOnLoad
    {
        public AuthService(Common.Models.Logging.ISptLogger<AuthService> logger, Core.Models.Spt.Config.HttpConfig httpConfig, Core.Utils.JsonUtil jsonUtil, IPasswordHasher passwordHasher) { }
        public System.Threading.Tasks.Task OnLoadAsync(System.Threading.CancellationToken stoppingToken) { throw null; }
    }

    [DI.Annotations.Injectable(DI.Annotations.InjectionType.Singleton, int.MaxValue)]
    public partial class ConfigEditorService
    {
        public ConfigEditorService(System.IServiceProvider serviceProvider, Core.Utils.JsonUtil jsonUtil, System.Collections.Generic.IEnumerable<IConfigEditorConfigProvider> configProviders) { }
        public void ApplyPresetToRuntime(string presetId) { }
        public System.Threading.Tasks.Task ApplyPresetToRuntimeAsync(string presetId) { throw null; }
        public string ApplyToRuntime(string configId, string json) { throw null; }
        public System.Threading.Tasks.Task<string> ApplyToRuntimeAsync(string configId, string json) { throw null; }
        public bool DeletePreset(string presetId) { throw null; }
        public string FormatJson(string configId, string json) { throw null; }
        public System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<Models.Configs.ConfigEditorConfigSummary>> GetConfigSummariesAsync() { throw null; }
        public Models.Configs.ConfigEditorPreset? GetPreset(string presetId) { throw null; }
        public int GetPresetCount() { throw null; }
        public System.Collections.Generic.IReadOnlyList<Models.Configs.ConfigEditorPreset> GetPresets() { throw null; }
        public System.Threading.Tasks.Task<Models.Configs.ConfigEditorSnapshot> GetSnapshotAsync(string configId) { throw null; }
        public Models.Configs.ConfigEditorPreset SavePreset(string configId, string name, string json) { throw null; }
        public System.Threading.Tasks.Task SaveToDiskAsync(string configId, string json) { throw null; }
        public void ValidateJson(string configId, string json) { }
    }
    public partial interface IConfigEditorConfigProvider
    {
        System.Collections.Generic.IEnumerable<Models.Configs.ConfigEditorConfigRegistration> GetConfigs();
    }

    public partial interface IPasswordHasher
    {
        string DummyHash { get; }

        string Hash(string password);
        bool IsEncodedHash(string value);
        bool Verify(string password, string encodedHash, out bool needsRehash);
    }

    [DI.Annotations.Injectable(DI.Annotations.InjectionType.Singleton, int.MaxValue)]
    public partial class WebLocalizationService : Core.Services.Locales.AbstractLocalisationService<WebLocalizationService>
    {
        public WebLocalizationService(Common.Models.Logging.ISptLogger<WebLocalizationService> logger, Core.Services.Locales.LocaleService localeService, Core.Utils.FileUtil fileUtil, Core.Utils.JsonUtil jsonUtil) : base(default!, default!) { }
        protected override void LoadLocales() { }
    }
}

namespace SPTarkov.Server.Web.Utils
{
    public static partial class JsonPropertyFlattener
    {
        public static System.Collections.Generic.IReadOnlyList<Models.Database.DatabaseProperty> BuildProperties(string propertiesJson) { throw null; }
    }
}