//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPTarkov.Common.Extensions
{
    public static partial class HttpContextExtensions
    {
        public static Microsoft.Extensions.Primitives.StringValues? GetHeaderIfExists(this Microsoft.AspNetCore.Http.HttpContext context, string key) { throw null; }
    }
    public static partial class ListExtensions
    {
        public static T PopFirst<T>(this System.Collections.Generic.IList<T> source) { throw null; }
        public static T PopLast<T>(this System.Collections.Generic.IList<T> source) { throw null; }
        public static System.Collections.Generic.List<T> Splice<T>(this System.Collections.Generic.List<T> source, int index, int count) { throw null; }
    }
    public static partial class MemberInfoExtensions
    {
        public static string GetJsonName(this System.Reflection.MemberInfo memberInfo) { throw null; }
    }
    public static partial class ObjectExtensions
    {
        public static object AddAllToExtensionData(this object obj, System.Collections.Generic.Dictionary<string, object> extensionData) { throw null; }
        public static object AddToExtensionData(this object obj, string key, object value) { throw null; }
        public static bool ContainsJsonProperty<T>(this object? obj, T key) { throw null; }
        public static System.Collections.Generic.Dictionary<string, object?> GetAllPropertiesAsDictionary(this object? obj) { throw null; }
        public static System.Collections.Generic.List<object> GetAllPropertyValuesAsList(this object? obj) { throw null; }
        public static T? GetByJsonProperty<T>(this object? obj, string? toLower) { throw null; }
        public static System.Collections.Generic.Dictionary<string, object> GetExtensionData(this object obj) { throw null; }
        public static object RemoveAllFromExtensionData(this object obj) { throw null; }
        public static object RemoveFromExtensionData(this object obj, string key) { throw null; }
        public static T? ToObject<T>(this System.Text.Json.JsonElement element) { throw null; }
        public static bool TryGetExtensionData(this object obj, out System.Collections.Generic.Dictionary<string, object>? extensionData) { throw null; }
    }
    public static partial class SptLoggerExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddSptLogger(this Microsoft.Extensions.DependencyInjection.IServiceCollection collection, bool isDevelop = false) { throw null; }
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddSptLoggerWithoutProvider(this Microsoft.Extensions.DependencyInjection.IServiceCollection collection, System.IServiceProvider earlyLoggerServiceProvider) { throw null; }
        public static Microsoft.Extensions.Hosting.IHostBuilder UseSptLoggerWithoutProvider(this Microsoft.Extensions.Hosting.IHostBuilder builder, System.IServiceProvider earlyLoggerServiceProvider) { throw null; }
    }
    public static partial class SptLogLevelExtensions
    {
        public static Spectre.Console.Color? GetBackgroundColor(this Microsoft.Extensions.Logging.LogLevel microsoftLogLevel) { throw null; }
        public static Spectre.Console.Color? GetTextColor(this Microsoft.Extensions.Logging.LogLevel microsoftLogLevel) { throw null; }
        extension(Microsoft.Extensions.Logging.LogLevel microsoftLogLevel)
        {
            public Spectre.Console.Color? GetTextColor() { throw null; }
            public Spectre.Console.Color? GetBackgroundColor() { throw null; }
            public Spectre.Console.Color? GetBackgroundColor() { throw null; }
            public Spectre.Console.Color? GetTextColor() { throw null; }
        }
    }
    public static partial class StringExtensions
    {
        public static bool RegexMatch(this string source, string regexString, out System.Text.RegularExpressions.Match? matchedString) { throw null; }
        public static string RegexReplace(this string source, string regexString, string newValue) { throw null; }
    }
}

namespace SPTarkov.Common.Json.Converters
{
    public sealed partial class BaseSptLoggerReferenceConverter : System.Text.Json.Serialization.JsonConverter<Models.Logging.BaseSptLoggerReference>
    {
        public override Models.Logging.BaseSptLoggerReference? Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) { throw null; }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, Models.Logging.BaseSptLoggerReference value, System.Text.Json.JsonSerializerOptions options) { }
    }
}

namespace SPTarkov.Common.Logger
{
    public sealed partial class SptEarlyLoggerFactory : Microsoft.Extensions.Logging.ILoggerFactory, System.IDisposable
    {
        public SptEarlyLoggerFactory(Microsoft.Extensions.Logging.ILoggerFactory loggerFactory, Microsoft.Extensions.DependencyInjection.ServiceProvider serviceProvider) { }
        public SptLoggerProvider Provider { get { throw null; } }
        public Microsoft.Extensions.DependencyInjection.ServiceProvider ServiceProvider { get { throw null; } }

        public void AddProvider(Microsoft.Extensions.Logging.ILoggerProvider provider) { }
        public Microsoft.Extensions.Logging.ILogger CreateLogger(string categoryName) { throw null; }
        public void Dispose() { }
    }

    public sealed partial class SPTLoggerDispatcher : System.IAsyncDisposable
    {
        public SPTLoggerDispatcher(Models.Logging.SptLoggerConfiguration config, System.Collections.Generic.IEnumerable<Models.Logging.ILogHandler> logHandlers) { }
        public System.Threading.Tasks.ValueTask DisposeAsync() { throw null; }
        public bool IsLogEnabled(Microsoft.Extensions.Logging.LogLevel level) { throw null; }
        public void Log(Models.Logging.SptLogMessage message) { }
    }

    public sealed partial class SptLoggerProvider : Microsoft.Extensions.Logging.ILoggerProvider, System.IDisposable, Microsoft.Extensions.Logging.ILoggerFactory
    {
        public SptLoggerProvider(SPTLoggerDispatcher dispatcher) { }
        public void AddProvider(Microsoft.Extensions.Logging.ILoggerProvider provider) { }
        public static SptEarlyLoggerFactory Create(bool isDevelop) { throw null; }
        public Microsoft.Extensions.Logging.ILogger CreateLogger(string categoryName) { throw null; }
        public void Dispose() { }
    }

    public sealed partial class SPTLoggerWrapper : Microsoft.Extensions.Logging.ILogger
    {
        public SPTLoggerWrapper(string category, SPTLoggerDispatcher dispatcher) { }
        public System.IDisposable? BeginScope<TState>(TState state) { throw null; }
        public bool IsEnabled(Microsoft.Extensions.Logging.LogLevel logLevel) { throw null; }
        public void Log<TState>(Microsoft.Extensions.Logging.LogLevel logLevel, Microsoft.Extensions.Logging.EventId eventId, TState state, System.Exception? exception, System.Func<TState, System.Exception?, string> formatter) { }
    }

    public sealed partial class SptLogger<T> : Models.Logging.ISptLogger<T>
    {
        public SptLogger(Models.Logging.SptLoggerConfiguration configuration, SPTLoggerDispatcher loggerDispatcher) { }
        public void Critical(string data, System.Exception? ex = null) { }
        public void Debug(string data, System.Exception? ex = null) { }
        public void Error(string data, System.Exception? ex = null) { }
        public void Info(string data, System.Exception? ex = null) { }
        public bool IsLogEnabled(Microsoft.Extensions.Logging.LogLevel level) { throw null; }
        public void Log(Microsoft.Extensions.Logging.LogLevel level, string data, Spectre.Console.Color? textColor = null, Spectre.Console.Color? backgroundColor = null, System.Exception? ex = null) { }
        public void LogWithColor(string data, Spectre.Console.Color? textColor = null, Spectre.Console.Color? backgroundColor = null, System.Exception? ex = null) { }
        public void OverrideCategory(string category) { }
        public void Success(string data, System.Exception? ex = null) { }
        public void Warning(string data, System.Exception? ex = null) { }
    }
}

namespace SPTarkov.Common.Logger.Handlers
{
    public abstract partial class BaseLogHandler : Models.Logging.ILogHandler, System.IAsyncDisposable
    {
        public abstract Models.Logging.LoggerType LoggerType { get; }

        public abstract System.Threading.Tasks.ValueTask DisposeAsync();
        protected string FormatMessage(string processedMessage, Models.Logging.SptLogMessage message, Models.Logging.BaseSptLoggerReference reference) { throw null; }
        protected string GetLoggerShortName(string logger) { throw null; }
        public abstract void Log(Models.Logging.SptLogMessage message, Models.Logging.BaseSptLoggerReference reference);
    }
}

namespace SPTarkov.Common.Models.Logging
{
    [System.Text.Json.Serialization.JsonConverter(typeof(Json.Converters.BaseSptLoggerReferenceConverter))]
    public abstract partial class BaseSptLoggerReference
    {
        [System.Text.Json.Serialization.JsonPropertyName("filters")]
        public System.Collections.Generic.List<SptLoggerFilter> Filters { get { throw null; } init { } }

        [System.Text.Json.Serialization.JsonPropertyName("format")]
        public required string Format { get { throw null; } init { } }

        [System.Text.Json.Serialization.JsonPropertyName("logLevel")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public required Microsoft.Extensions.Logging.LogLevel LogLevel { get { throw null; } init { } }

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public required LoggerType Type { get { throw null; } init { } }

        public virtual System.Text.CompositeFormat GetCompiledFormat() { throw null; }
    }
    public sealed partial class ConsoleSptLoggerReference : BaseSptLoggerReference
    {
    }

    public sealed partial class FileLogger
    {
    }
    public sealed partial class FileSptLoggerReference : BaseSptLoggerReference
    {
        [System.Text.Json.Serialization.JsonPropertyName("filePath")]
        public required string FilePath { get { throw null; } init { } }

        [System.Text.Json.Serialization.JsonPropertyName("filePattern")]
        public required string FilePattern { get { throw null; } init { } }

        [System.Text.Json.Serialization.JsonPropertyName("maxFileSizeMB")]
        public int MaxFileSizeMb { get { throw null; } init { } }

        [System.Text.Json.Serialization.JsonPropertyName("maxRollingFiles")]
        public int MaxRollingFiles { get { throw null; } init { } }
    }

    public partial interface ILogHandler : System.IAsyncDisposable
    {
        LoggerType LoggerType { get; }

        void Log(SptLogMessage message, BaseSptLoggerReference reference);
    }

    public partial interface ISptLogger<T>
    {
        void Critical(string data, System.Exception? ex = null);
        void Debug(string data, System.Exception? ex = null);
        void Error(string data, System.Exception? ex = null);
        void Info(string data, System.Exception? ex = null);
        bool IsLogEnabled(Microsoft.Extensions.Logging.LogLevel level);
        void Log(Microsoft.Extensions.Logging.LogLevel level, string data, Spectre.Console.Color? textColor = null, Spectre.Console.Color? backgroundColor = null, System.Exception? ex = null);
        void LogWithColor(string data, Spectre.Console.Color? textColor = null, Spectre.Console.Color? backgroundColor = null, System.Exception? ex = null);
        void Success(string data, System.Exception? ex = null);
        void Warning(string data, System.Exception? ex = null);
    }

    public enum LoggerType
    {
        File = 0,
        Console = 1
    }

    public enum MatchingType
    {
        Literal = 0,
        Regex = 1
    }

    public sealed partial class SptLoggerConfiguration
    {
        [System.Text.Json.Serialization.JsonPropertyName("loggers")]
        public System.Collections.Generic.List<BaseSptLoggerReference> Loggers { get { throw null; } init { } }
    }
    public sealed partial class SptLoggerFilter
    {
        [System.Text.Json.Serialization.JsonPropertyName("matchingType")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public required MatchingType MatchingType { get { throw null; } init { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public required string Name { get { throw null; } init { } }

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public required SptLoggerFilterType Type { get { throw null; } init { } }

        public override bool Equals(object? obj) { throw null; }
        public override int GetHashCode() { throw null; }
    }
    public static partial class SptLoggerFilterExtensions
    {
        public static bool CanLog(this Microsoft.Extensions.Logging.LogLevel logLevel, Microsoft.Extensions.Logging.LogLevel messageLevel) { throw null; }
        public static bool Match(this SptLoggerFilter filter, SptLogMessage message) { throw null; }
    }
    public enum SptLoggerFilterType
    {
        Exclude = 0,
        Include = 1
    }

    public partial record SptLogMessage(string Logger, System.DateTime LogTime, Microsoft.Extensions.Logging.LogLevel LogLevel, int threadId, string? threadName, string Message, System.Exception? Exception = null, Spectre.Console.Color? TextColor = null, Spectre.Console.Color? BackgroundColor = null)
    {
    }
}

namespace SPTarkov.Common.Semver
{
    public partial interface ISemVer
    {
        string MaxSatisfying(System.Collections.Generic.IEnumerable<SemanticVersioning.Version> versions);
        string MaxSatisfying(System.Collections.Generic.List<SemanticVersioning.Version> versions);
        string MaxSatisfying(string version, System.Collections.Generic.IEnumerable<SemanticVersioning.Version> versions);
        string MaxSatisfying(string version, System.Collections.Generic.List<SemanticVersioning.Version> versions);
        bool Satisfies(SemanticVersioning.Version version, SemanticVersioning.Range testRange);
    }
}

namespace SPTarkov.Common.Semver.Implementations
{
    public partial class SemanticVersioningSemVer : ISemVer
    {
        public string MaxSatisfying(System.Collections.Generic.IEnumerable<SemanticVersioning.Version> versions) { throw null; }
        public string MaxSatisfying(System.Collections.Generic.List<SemanticVersioning.Version> versions) { throw null; }
        public string MaxSatisfying(string version, System.Collections.Generic.IEnumerable<SemanticVersioning.Version> versions) { throw null; }
        public string MaxSatisfying(string version, System.Collections.Generic.List<SemanticVersioning.Version> versions) { throw null; }
        public bool Satisfies(SemanticVersioning.Version version, SemanticVersioning.Range testRange) { throw null; }
    }
}