//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPTarkov.DI
{
    public sealed partial record DependencyInjectionContainer
    {
        public DependencyInjectionContainer(Annotations.Injectable injectable, System.Type parentType, System.Type type) { }
        public Annotations.Injectable InjectableAttribute { get { throw null; } init { } }
        public System.Type ParentType { get { throw null; } init { } }
        public System.Type Type { get { throw null; } init { } }
    }
    public partial class DependencyInjectionHandler
    {
        public DependencyInjectionHandler(Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection) { }
        public void AddInjectableTypesFromAssemblies(System.Collections.Generic.IEnumerable<System.Reflection.Assembly> assemblies) { }
        public void AddInjectableTypesFromAssembly(System.Reflection.Assembly assembly) { }
        public void AddInjectableTypesFromTypeAssembly(System.Type type) { }
        public void AddInjectableTypesFromTypeList(System.Collections.Generic.IEnumerable<System.Type> types) { }
        public void InjectAll() { }
    }
}

namespace SPTarkov.DI.Annotations
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    public partial class Injectable : System.Attribute
    {
        public Injectable(InjectionType injectionType = InjectionType.Transient, int typePriority = int.MaxValue) { }
        public InjectionType InjectionType { get { throw null; } init { } }
        public int TypePriority { get { throw null; } init { } }
    }

    public enum InjectionType
    {
        HostedService = 0,
        Singleton = 1,
        Transient = 2,
        Scoped = 3
    }
}

namespace SPTarkov.DI.Extensions
{
    public static partial class DependencyInjectionExtensions
    {
        public static int GetTypePriority<T>(this T type) { throw null; }
    }
}