//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPTarkov.Reflection.CodeWrapper
{
    public partial class Code
    {
        public Code(System.Reflection.Emit.OpCode opCode, object operandTarget) { }
        public Code(System.Reflection.Emit.OpCode opCode, System.Type callerType, object operandTarget, System.Type[] parameters = null) { }
        public Code(System.Reflection.Emit.OpCode opCode, System.Type callerType) { }
        public Code(System.Reflection.Emit.OpCode opCode) { }
        public System.Type? CallerType { get { throw null; } }
        public bool HasOperand { get { throw null; } }
        public System.Reflection.Emit.OpCode OpCode { get { throw null; } }
        public object? OperandTarget { get { throw null; } }
        public System.Type[]? Parameters { get { throw null; } }

        public virtual System.Reflection.Emit.Label? GetLabel() { throw null; }
    }
    public partial class CodeGenerator
    {
        public static System.Collections.Generic.List<HarmonyLib.CodeInstruction> GenerateInstructions(System.Collections.Generic.List<Code> codes) { throw null; }
    }
    public partial class CodeWithLabel : Code
    {
        public CodeWithLabel(System.Reflection.Emit.OpCode opCode, System.Reflection.Emit.Label label, object operandTarget) : base(default) { }
        public CodeWithLabel(System.Reflection.Emit.OpCode opCode, System.Reflection.Emit.Label label, System.Type callerType, object operandTarget, System.Type[] parameters = null) : base(default) { }
        public CodeWithLabel(System.Reflection.Emit.OpCode opCode, System.Reflection.Emit.Label label, System.Type callerType) : base(default) { }
        public CodeWithLabel(System.Reflection.Emit.OpCode opCode, System.Reflection.Emit.Label label) : base(default) { }
        public System.Reflection.Emit.Label Label { get { throw null; } }

        public override System.Reflection.Emit.Label? GetLabel() { throw null; }
    }
}

namespace SPTarkov.Reflection.Patching
{
    public abstract partial class AbstractPatch : IRuntimePatch
    {
        protected AbstractPatch(string? name = null) { }
        public string HarmonyId { get { throw null; } }
        public bool IsActive { get { throw null; } }
        public bool IsManaged { get { throw null; } }
        public bool IsYourPatch { get { throw null; } }
        public System.Reflection.MethodBase? TargetMethod { get { throw null; } }

        public void Disable() { }
        public void Enable() { }
        protected abstract System.Reflection.MethodBase? GetTargetMethod();
    }

    [System.AttributeUsage(System.AttributeTargets.Class)]
    public partial class DebugPatchAttribute : System.Attribute
    {
    }

    [System.AttributeUsage(System.AttributeTargets.Class)]
    public partial class IgnoreAutoPatchAttribute : System.Attribute
    {
    }

    public partial interface IRuntimePatch
    {
        string HarmonyId { get; }

        bool IsActive { get; }

        bool IsManaged { get; }

        bool IsYourPatch { get; }

        void Disable();
        void Enable();
    }

    public partial class PatchException : System.Exception
    {
        public PatchException(string message, System.Exception innerException) { }
        public PatchException(string message) { }
    }

    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchFinalizerAttribute : System.Attribute
    {
    }

    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchIlManipulatorAttribute : System.Attribute
    {
    }

    [DI.Annotations.Injectable(DI.Annotations.InjectionType.Transient, int.MaxValue)]
    public partial class PatchManager
    {
        public bool AutoPatch { get { throw null; } set { } }
        public string? PatcherName { get { throw null; } set { } }

        public void AddPatch(AbstractPatch patch) { }
        public void AddPatches(System.Collections.Generic.List<AbstractPatch> patchList) { }
        public void DisablePatch(AbstractPatch patch) { }
        public void DisablePatches() { }
        public void EnablePatch(AbstractPatch patch) { }
        public void EnablePatches() { }
    }
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchPostfixAttribute : System.Attribute
    {
    }

    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchPrefixAttribute : System.Attribute
    {
    }

    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchTranspilerAttribute : System.Attribute
    {
    }
}