//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPT.Core
{
    [BepInEx.BepInPlugin("com.SPT.core", "SPT.Core", "4.1.2")]
    public partial class SPTCorePlugin : BepInEx.BaseUnityPlugin
    {
        public void Awake() { }
    }
}

namespace SPT.Core.Models
{
    public partial class FakeFileCheckerResult : FilesChecker.ICheckResult
    {
        public System.TimeSpan ElapsedTime { get { throw null; } }
        public System.Exception Exception { get { throw null; } }
    }
}

namespace SPT.Core.Patches
{
    public partial class BattlEyePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
    }

    public partial class ConsistencyMultiPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
    }

    public partial class ConsistencySinglePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
    }

    public partial class SslCertificatePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
    }

    public partial class UnityWebRequestPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
    }

    public partial class WebSocketSslValidationPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref bool __result) { throw null; }
    }
}