//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPT.SinglePlayer
{
    [BepInEx.BepInPlugin("com.SPT.singleplayer", "SPT.Singleplayer", "4.1.2")]
    public partial class SPTSingleplayerPlugin : BepInEx.BaseUnityPlugin
    {
        public void Awake() { }
        public void Start() { }
    }
}

namespace SPT.SinglePlayer.Models.MainMenu
{
    public partial class ModdedTraderListResponse
    {
        [JetBrains.Annotations.CanBeNull]
        public System.Collections.Generic.List<string> ModdedTraders;
    }
}

namespace SPT.SinglePlayer.Models.ScavMode
{
    public partial class ExitChanges
    {
        public int? Chance { get { throw null; } set { } }
        public int? MaxTime { get { throw null; } set { } }
        public int? MinTime { get { throw null; } set { } }
        public string Name { get { throw null; } set { } }
    }
    public partial class RaidTimeRequest
    {
        public RaidTimeRequest(EFT.ESideType side, string location) { }
        public string Location { get { throw null; } set { } }
        public EFT.ESideType Side { get { throw null; } set { } }
    }
    public partial class RaidTimeResponse
    {
        public System.Collections.Generic.List<ExitChanges> ExitChanges { get { throw null; } set { } }
        public int? NewSurviveTimeSeconds { get { throw null; } set { } }
        public int OriginalSurvivalTimeSeconds { get { throw null; } set { } }
        public int RaidTimeMinutes { get { throw null; } set { } }
    }
    public partial class SellAllRequest
    {
        [Newtonsoft.Json.JsonProperty("Action")]
        public string Action;
        [Newtonsoft.Json.JsonProperty("fromOwner")]
        public EFT.OwnerInfo FromOwner;
        [Newtonsoft.Json.JsonProperty("toOwner")]
        public EFT.OwnerInfo ToOwner;
        [Newtonsoft.Json.JsonProperty("totalValue")]
        public int TotalValue;
    }
}

namespace SPT.SinglePlayer.Patches.MainMenu
{
    public partial class ArmorDamageCounterPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(EFT.Ballistics.DamageInfo damageInfo) { }
    }

    public partial class DisableBuffLoggingPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(EFT.InventoryLogic.BuffComponent __instance) { }
    }

    public partial class DisableMatchmakerPlayerPreviewButtonsPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(ref EFT.UI.Matchmaker.RaidGroupContextInteractions contextInteractions) { }
    }

    public partial class DisableUseBSGServersCheckbox : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(ref EFT.UI.UpdatableToggle ____onlineModeToggle) { }
    }

    public partial class DisableWelcomeToPVEModeMessagePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref bool __result, string variable) { throw null; }
    }

    public partial class ForceRaidModeToLocalPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void Prefix(ref EFT.RaidSettings ____raidSettings, bool canEscape) { }
    }

    public partial class PluginErrorNotifierPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix() { }
    }

    public static partial class ReadyButtonPatches
    {
        public static void Patch() { }
        public partial class DisableMatchmakerInsuranceReadyPatch : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
            [Reflection.Patching.PatchPostfix]
            public static void PatchPostfix(EFT.UI.DefaultUIButton ____readyButton) { }
        }

        public partial class DisableMatchmakerOfflineRaidReadyPatch : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
            [Reflection.Patching.PatchPostfix]
            public static void PatchPostfix(EFT.UI.DefaultUIButton ____readyButton) { }
        }

        public partial class DisableReadyLocationReadyPatch : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
            [Reflection.Patching.PatchPostfix]
            public static void PatchPostfix(EFT.UI.DefaultUIButton ____readyButton) { }
        }
    }
    public partial class RemoveClothingItemExternalObtainLabelPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
    }

    public partial class RemoveStashUpgradeLabelPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void Postfix(EFT.UI.InventoryScreen __instance) { }
    }

    public partial class RemoveStashUpgradeLabelPatch2 : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void Postfix(EFT.UI.MenuUI __instance) { }
    }
}

namespace SPT.SinglePlayer.Patches.RaidFix
{
    public partial class DisableHideoutCounterResetPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchTranspiler]
        protected static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> PatchTranspiler(System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> originalInstructions) { throw null; }
    }

    public partial class EmptyInfilFixPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(ref string ____entryPoint) { }
    }

    public partial class FixDisableBossSpawningOptionPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(EFT.WavesSettings wavesSettings, BossLocationSpawn[] bossLocationSpawn, ref BossLocationSpawn[] __result) { throw null; }
    }

    public partial class FixKeyAlreadyExistsErrorOnAchievementPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool Prefix(EFT.Achievements.Achievement achievement, bool notify, EFT.Achievements.AchievementsController __instance) { throw null; }
    }

    public partial class OverrideMaxAiAliveInRaidValuePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPreFix(ref int maxCount) { }
    }

    public partial class PmcBotSidePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(ref EFT.Profile __result) { }
    }

    public partial class QuestAchievementRewardInRaidPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
    }

    public partial class RemoveTransitionRaidModeSetPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchTranspiler]
        protected static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> PatchTranspiler(System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> originalInstructions) { throw null; }
    }

    public partial class RemoveUsedBotProfilePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref bool withDelete) { throw null; }
    }

    public partial class TinnitusFixPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix() { throw null; }
    }
}

namespace SPT.SinglePlayer.Patches.ScavMode
{
    public partial class DisablePMCExtractsForScavsPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostFix() { }
    }

    public partial class GetProfileAtEndOfRaidPatch : Reflection.Patching.ModulePatch
    {
        public static EFT.ProfileDescriptor ProfileDescriptor { get { throw null; } }

        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(LocalGame __instance, EFT.ExitStatus exitStatus) { }
    }

    public partial class LoadOfflineRaidScreenPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchTranspiler]
        public static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> PatchTranspiler(System.Reflection.Emit.ILGenerator generator, System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions) { throw null; }
    }

    public partial class ScavExfilPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(EFT.Profile profile, CommonAssets.Scripts.Game.ExfiltrationController __instance, ref EFT.Interactive.ExfiltrationPoint[] __result) { throw null; }
    }

    public partial class ScavIsPlayerEnemyPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool Prefix(BotsGroup __instance, EFT.IPlayer player, ref bool __result) { throw null; }
    }

    public partial class ScavLateStartPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref EFT.RaidSettings ____raidSettings) { throw null; }
    }

    public partial class ScavPrefabLoadPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchTranspiler]
        public static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> PatchTranspile(System.Reflection.Emit.ILGenerator generator, System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions) { throw null; }
    }

    public partial class ScavPrestigeFixPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(ref EFT.Profile profile) { }
    }

    public partial class ScavProfileLoadPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchTranspiler]
        public static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> PatchTranspile(System.Reflection.Emit.ILGenerator generator, System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions) { throw null; }
    }

    public partial class ScavRepAdjustmentPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(EFT.Ballistics.DamageInfo damage, string playerProfileId) { }
    }

    public partial class ScavSellAllPriceStorePatch : Reflection.Patching.ModulePatch
    {
        public static int StoredPrice;
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(EFT.UI.ScavengerInventoryScreen __instance) { }
    }

    public partial class ScavSellAllRequestPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(EFT.ClientBackendSession __instance, ref System.Threading.Tasks.Task<Comfort.Common.IResult> __result, string playerId, string petId) { throw null; }
    }

    public partial class SendPlayerScavProfileToServerAfterRaidPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(EFT.SessionResultShowOperation __instance) { }
    }
}

namespace SPT.SinglePlayer.Utils.InRaid
{
    public static partial class RaidChangesUtil
    {
        public static bool HaveChangesBeenApplied { get { throw null; } }
        public static bool IsScavRaid { get { throw null; } }
        public static string LocationId { get { throw null; } }
        public static int NewEscapeTimeMinutes { get { throw null; } }
        public static int NewEscapeTimeSeconds { get { throw null; } }
        public static int NewSurvivalTimeSeconds { get { throw null; } }
        public static int OriginalEscapeTimeMinutes { get { throw null; } }
        public static int OriginalEscapeTimeSeconds { get { throw null; } }
        public static int OriginalSurvivalTimeSeconds { get { throw null; } }
        public static System.DateTime RaidChangesAppliedUtcTime { get { throw null; } }
        public static int RaidTimeReductionMinutes { get { throw null; } }
        public static int RaidTimeReductionSeconds { get { throw null; } }
        public static float RaidTimeRemainingFraction { get { throw null; } }
        public static int SurvivalTimeReductionSeconds { get { throw null; } }
    }
    public static partial class RaidTimeUtil
    {
        public static float GetElapsedRaidSeconds() { throw null; }
        public static float GetRaidTimeRemainingFraction() { throw null; }
        public static float GetRemainingRaidSeconds() { throw null; }
        public static float GetSecondsSinceSpawning() { throw null; }
        public static bool HasRaidLoaded() { throw null; }
        public static bool HasRaidStarted() { throw null; }
    }
}

namespace SPT.SinglePlayer.Utils.MainMenu
{
    public static partial class TraderCustomizationManager
    {
        public static void AddModdedTraders() { }
    }
}