//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPT.PrePatch
{
    public sealed partial class EnumEntryDefinition
    {
        [Newtonsoft.Json.JsonProperty("constantName")]
        public string ConstantName { get { throw null; } set { } }

        [Newtonsoft.Json.JsonProperty("constantValue")]
        public long ConstantValue { get { throw null; } set { } }

        [Newtonsoft.Json.JsonProperty("enumType")]
        public string EnumType { get { throw null; } set { } }

        [Newtonsoft.Json.JsonProperty("jsonEnumName")]
        public string JsonEnumName { get { throw null; } set { } }
    }
    public static partial class EnumPatcher
    {
        public static void PatchEnums(BepInEx.Logging.ManualLogSource logger, ref Mono.Cecil.AssemblyDefinition assembly, System.Collections.Generic.IReadOnlyCollection<EnumEntryDefinition> entries) { }
    }
    public sealed partial class ModLoaderException : System.Exception
    {
        public ModLoaderException(string message, System.Exception innerException) { }
        public ModLoaderException(string message) { }
    }

    public static partial class SptPrePatcher
    {
        public static System.Collections.Generic.IEnumerable<string> TargetDLLs { get { throw null; } }

        public static void Patch(ref Mono.Cecil.AssemblyDefinition assembly) { }
    }
}