//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPT.Common
{
    public static partial class SPTPluginInfo
    {
        public const string PLUGIN_VERSION = "4.1.2";
    }
}

namespace SPT.Common.Http
{
    public partial class Client
    {
        public Client(string address, string accountId, int retries = 3) { }
        public System.Net.Http.HttpClient HttpClient { get { throw null; } }

        public System.Net.Http.HttpRequestMessage CreateNewHttpRequest(System.Net.Http.HttpMethod method, string path) { throw null; }
        public System.Threading.Tasks.Task DownloadAsync(string path, string filePath, System.Action<DownloadProgress> progressCallback = null) { throw null; }
        public System.Threading.Tasks.Task<byte[]> GetAsync(string path) { throw null; }
        public System.Threading.Tasks.Task<byte[]> PostAsync(string path, byte[] data, bool compress = true) { throw null; }
        public System.Threading.Tasks.Task<byte[]> PutAsync(string path, byte[] data, bool compress = true) { throw null; }
        protected System.Threading.Tasks.Task<byte[]> SendAsync(System.Net.Http.HttpMethod method, string path, byte[] data, bool zipped = true) { throw null; }
        protected System.Threading.Tasks.Task<byte[]> SendWithRetriesAsync(System.Net.Http.HttpMethod method, string path, byte[] data, bool compress = true) { throw null; }
    }
    public partial class DownloadProgress
    {
        public string DownloadSpeed { get { throw null; } set { } }
        public string FileSizeInfo { get { throw null; } set { } }

        public static string FormatDownloadSpeed(double bytesPerSecond) { throw null; }
        public static string FormatFileSize(long bytes) { throw null; }
    }
    public static partial class RequestHandler
    {
        public static readonly string Host;
        public static readonly Client HttpClient;
        public static readonly bool IsLocal;
        public static readonly string SessionId;
        public static byte[] GetData(string path) { throw null; }
        public static System.Threading.Tasks.Task<byte[]> GetDataAsync(string path) { throw null; }
        public static string GetJson(string path) { throw null; }
        public static System.Threading.Tasks.Task<string> GetJsonAsync(string path) { throw null; }
        public static string PostJson(string path, string json) { throw null; }
        public static System.Threading.Tasks.Task<string> PostJsonAsync(string path, string json) { throw null; }
        public static string PutJson(string path, string json) { throw null; }
        public static System.Threading.Tasks.Task<string> PutJsonAsync(string path, string json) { throw null; }
    }
    public partial class ServerConfig
    {
        public ServerConfig(string backendUrl, string matchingVersion, string version) { }
        public string BackendUrl { get { throw null; } }
        public string MatchingVersion { get { throw null; } }
        public string Version { get { throw null; } }
    }
}

namespace SPT.Common.Models
{
    public partial class FakeCertificateHandler : UnityEngine.Networking.CertificateHandler
    {
        protected override bool ValidateCertificate(byte[] certificateData) { throw null; }
    }
}

namespace SPT.Common.Models.Logging
{
    public enum EServerLogBackgroundColor
    {
        Black = 40,
        Red = 41,
        Green = 42,
        Yellow = 43,
        Blue = 44,
        Magenta = 45,
        Cyan = 46,
        White = 47,
        Default = 49
    }

    public enum EServerLogLevel
    {
        Trace = 0,
        Debug = 1,
        Information = 2,
        Warning = 3,
        Error = 4,
        Critical = 5
    }

    public enum EServerLogTextColor
    {
        Black = 30,
        Red = 31,
        Green = 32,
        Yellow = 33,
        Blue = 34,
        Magenta = 35,
        Cyan = 36,
        White = 37,
        Gray = 90
    }

    public partial class ServerLogRequest
    {
        public EServerLogBackgroundColor BackgroundColor { get { throw null; } set { } }
        public EServerLogTextColor Color { get { throw null; } set { } }
        public EServerLogLevel Level { get { throw null; } set { } }
        public string Message { get { throw null; } set { } }
        public string Source { get { throw null; } set { } }
    }
}

namespace SPT.Common.Utils
{
    public static partial class Json
    {
        public static T Deserialize<T>(string json) { throw null; }
        public static string Serialize<T>(T data) { throw null; }
        public static string SerializeIndented<T>(T data) { throw null; }
    }
    public static partial class ServerLog
    {
        public static void Custom(string source, string message, Models.Logging.EServerLogTextColor color = Models.Logging.EServerLogTextColor.White, Models.Logging.EServerLogBackgroundColor backgroundColor = Models.Logging.EServerLogBackgroundColor.Default) { }
        public static void Debug(string source, string message) { }
        public static void Error(string source, string message) { }
        public static void Info(string source, string message) { }
        public static void Log(string source, string message, Models.Logging.EServerLogLevel level = Models.Logging.EServerLogLevel.Information, Models.Logging.EServerLogTextColor color = Models.Logging.EServerLogTextColor.White, Models.Logging.EServerLogBackgroundColor backgroundColor = Models.Logging.EServerLogBackgroundColor.Default) { }
        public static void Success(string source, string message) { }
        public static void Warn(string source, string message) { }
    }
    public static partial class VFS
    {
        public static string Cwd { get { throw null; } }

        public static string Combine(string path1, string path2) { throw null; }
        public static void CreateDirectory(string filepath) { }
        public static void DeleteDirectory(string filepath) { }
        public static void DeleteFile(string filepath) { }
        public static bool Exists(string filepath) { throw null; }
        public static string FromCwd(this string filepath) { throw null; }
        public static string[] GetDirectories(string filepath) { throw null; }
        public static string GetDirectory(this string filepath) { throw null; }
        public static string GetFile(this string filepath) { throw null; }
        public static string GetFileExtension(this string filepath) { throw null; }
        public static string GetFileName(this string filepath) { throw null; }
        public static string[] GetFiles(string filepath) { throw null; }
        public static int GetFilesCount(string filepath) { throw null; }
        public static void MoveFile(string a, string b) { }
        public static byte[] ReadFile(string filepath) { throw null; }
        public static System.Threading.Tasks.Task<byte[]> ReadFileAsync(string filepath) { throw null; }
        public static string ReadTextFile(string filepath) { throw null; }
        public static System.Threading.Tasks.Task<string> ReadTextFileAsync(string filepath) { throw null; }
        public static void WriteFile(string filepath, byte[] data) { }
        public static System.Threading.Tasks.Task WriteFileAsync(string filepath, byte[] data) { throw null; }
        public static void WriteTextFile(string filepath, string data, bool append = false) { }
    }
    public static partial class Zlib
    {
        public static byte[] Compress(byte[] data, ZlibCompression level) { throw null; }
        public static byte[] Decompress(byte[] data) { throw null; }
        public static bool IsCompressed(byte[] data) { throw null; }
    }
    public enum ZlibCompression
    {
        Store = 0,
        Fastest = 1,
        Fast = 3,
        Normal = 5,
        Ultra = 7,
        Maximum = 9
    }
}