//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace <global namespace>
{
    public partial class BundleUtils : UnityEngine.MonoBehaviour
    {
        public static global::BundleUtils Create() { throw null; }
        public void Dispose() { }
        public void Init(int length) { }
        public void OnGUI() { }
        public void SetDownloadProgress(SPT.Common.Http.DownloadProgress progress) { }
        public void SetProgress(int progress, string fileName) { }
    }
}

namespace SPT.Custom
{
    [BepInEx.BepInPlugin("com.SPT.custom", "SPT.Custom", "4.1.2")]
    public partial class SPTCustomPlugin : BepInEx.BaseUnityPlugin
    {
        public void Awake() { }
    }
}

namespace SPT.Custom.CustomAI
{
    public partial class AIBrainSpawnWeightAdjustment
    {
        public AIBrainSpawnWeightAdjustment(BepInEx.Logging.ManualLogSource logger) { }
        public EFT.WildSpawnType GetAssaultScavWildSpawnType(EFT.BotOwner botOwner, string currentMapName) { throw null; }
        public EFT.WildSpawnType GetPmcWildSpawnType(EFT.BotOwner botOwner_0, EFT.WildSpawnType pmcType, string currentMapName) { throw null; }
        public EFT.WildSpawnType GetRandomisedPlayerScavType(EFT.BotOwner botOwner, string currentMapName) { throw null; }
        public partial class AIBrains
        {
            public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, int>> assault { get { throw null; } set { } }
            public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, int>> playerScav { get { throw null; } set { } }
            public System.Collections.Generic.Dictionary<EFT.WildSpawnType, System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, int>>> pmc { get { throw null; } set { } }
        }
    }
    public static partial class AIExtensions
    {
        public static bool ContainsPlayer(this System.Collections.Generic.IEnumerable<EFT.IPlayer> players, EFT.IPlayer playerToCheck) { throw null; }
        public static System.Collections.Generic.List<EFT.BotOwner> GetAllMembers(this BotsGroup group) { throw null; }
        public static bool HasMainProfileNickname(this EFT.BotOwner botOwner) { throw null; }
        public static bool IsPMC(this EFT.BotOwner botOwner) { throw null; }
        public static bool IsSimulatedPlayerScav(this EFT.BotOwner botOwner) { throw null; }
    }
    public partial class PmcFoundInRaidEquipment
    {
        public PmcFoundInRaidEquipment(BepInEx.Logging.ManualLogSource logger) { }
        public void ConfigurePMCFindInRaidStatus(EFT.BotOwner ___botOwner_0) { }
    }
}

namespace SPT.Custom.Models
{
    [System.Runtime.Serialization.DataContract]
    public partial struct BundleItem
    {
        [System.Runtime.Serialization.DataMember(Name = "crc")]
        public uint Crc;
        [System.Runtime.Serialization.DataMember(Name = "dependencies")]
        public string[] Dependencies;
        [System.Runtime.Serialization.DataMember(Name = "filename")]
        public string FileName;
        [System.Runtime.Serialization.DataMember(Name = "modpath")]
        public string ModPath;
        public BundleItem(string filename, uint crc, string[] dependencies, string modpath = "") { }
    }

    public partial class ClientMod
    {
        [Newtonsoft.Json.JsonProperty("modGUID")]
        public string GUID { get { throw null; } set { } }

        [Newtonsoft.Json.JsonProperty("modName")]
        public string Name { get { throw null; } set { } }

        [Newtonsoft.Json.JsonProperty("modVersion")]
        public System.Version Version { get { throw null; } set { } }
    }
    public partial class ClientModsRequest
    {
        [Newtonsoft.Json.JsonProperty("activeClientMods")]
        public System.Collections.Generic.List<ClientMod> ActiveClientMods;
        public ClientModsRequest(System.Collections.Generic.List<ClientMod> activeMods) { }
    }
    public partial class CrcCacheEntry
    {
        public uint Crc { get { throw null; } set { } }
        public long Size { get { throw null; } set { } }
    }
    public partial class DefaultRaidSettings
    {
        public EFT.Bots.EBotAmount AiAmount;
        public EFT.Bots.EBotDifficulty AiDifficulty;
        public bool BossEnabled;
        public bool EnablePve;
        public bool RandomTime;
        public bool RandomWeather;
        public bool ScavWars;
        public bool TaggedAndCursed;
        public DefaultRaidSettings(EFT.Bots.EBotAmount aiAmount, EFT.Bots.EBotDifficulty aiDifficulty, bool bossEnabled, bool scavWars, bool taggedAndCursed, bool enablePve, bool randomWeather, bool randomTime) { }
    }
    public partial class DifficultyInfo
    {
        public object this[string key] { get { throw null; } }
    }
    public partial struct LoggingLevelResponse
    {
        private int _dummyPrimitive;
        public bool sendToServer { get { throw null; } set { } }
        public int verbosity { get { throw null; } set { } }
    }

    public partial struct ReleaseResponse
    {
        private object _dummy;
        private int _dummyPrimitive;
        public string betaDisclaimerAcceptText { get { throw null; } set { } }
        public string betaDisclaimerText { get { throw null; } set { } }
        public float betaDisclaimerTimeoutDelay { get { throw null; } set { } }
        public string clientModsLoadedDebugText { get { throw null; } set { } }
        public string clientModsLoadedText { get { throw null; } set { } }
        public string illegalPluginsExceptionText { get { throw null; } set { } }
        public string illegalPluginsLoadedText { get { throw null; } set { } }
        public bool isBeta { get { throw null; } set { } }
        public bool isModdable { get { throw null; } set { } }
        public bool isModded { get { throw null; } set { } }
        public string releaseSummaryText { get { throw null; } set { } }
        public string serverModsLoadedDebugText { get { throw null; } set { } }
        public string serverModsLoadedText { get { throw null; } set { } }
    }

    public partial struct VersionResponse
    {
        private object _dummy;
        private int _dummyPrimitive;
        public string Version { get { throw null; } set { } }
    }
}

namespace SPT.Custom.Patches
{
    public partial class AddOfferFilterHangPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool Prefix(EFT.UI.Ragfair.RagFair __instance) { throw null; }
    }

    public partial class AddTraitorScavsPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref BotsGroup __result, EFT.BotOwner bot, BotZone zone, EFT.BotSpawner __instance) { throw null; }
    }

    public partial class AllowAirdropsInPvEPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref int __result) { throw null; }
    }

    public partial class BetaLogoPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(EFT.Profile profile) { }
    }

    public partial class BetaLogoPatch2 : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(ref TMPro.TextMeshProUGUI ____label, EFT.Profile ___profile_0) { }
    }

    public partial class BetaLogoPatch3 : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(int screenHeight, int screenWidth, int rectHeight, int rectWidth, ref UnityEngine.Vector2 __result) { throw null; }
    }

    public partial class BotDifficultyPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref string __result, BotDifficulty botDifficulty, EFT.WildSpawnType role, bool isPve) { throw null; }
    }

    public partial class BotsControllerInitPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(EFT.BotsController __instance, JsonType.LocationSettings.Location.BotLocationEvents events) { }
    }

    public partial class BotsEventsControllerActivatePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(BotsEventsController __instance) { throw null; }
    }

    public partial class CopyPmcQuestsAndWishlistToPlayerScavPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix() { }
    }

    public partial class CoreDifficultyPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref string __result) { throw null; }
    }

    public partial class CustomAiPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostFix(EFT.WildSpawnType __state, StandartBotBrain __instance) { }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(out EFT.WildSpawnType __state, StandartBotBrain __instance) { throw null; }
    }

    public partial class DisableGameModeAdjustButtonPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ESessionMode sessionMode, EFT.Profile profile, ref UnityEngine.GameObject ____notAvailableState) { throw null; }
    }

    public partial class DisableNonHalloweenExitsDuringEventPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix() { }
    }

    public partial class EasyAssetsPatch : Reflection.Patching.ModulePatch
    {
        public static string GetPairKey(System.Collections.Generic.KeyValuePair<string, Models.BundleItem> x) { throw null; }
        public static UnityEngine.Build.Pipeline.BundleDetails GetPairValue(System.Collections.Generic.KeyValuePair<string, Models.BundleItem> x) { throw null; }
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref System.Threading.Tasks.Task<Diz.Resources.EasyAssets> __result, UnityEngine.GameObject gameObject, Diz.Resources.IBundleLock bundleLock, string defaultKey, string rootPath, string platformName, System.Func<string, bool> shouldExclude, System.Func<string, System.Threading.Tasks.Task> bundleCheck) { throw null; }
    }

    public partial class EasyBundlePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(Diz.Resources.EasyBundle __instance, string key, string rootPath, UnityEngine.Build.Pipeline.CompatibilityAssetBundleManifest manifest, Diz.Resources.IBundleLock bundleLock) { }
    }

    public partial class EnableInfectionUIPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(EFT.RaidSettings raidSettings, EFT.UI.Matchmaker.LocationConditionsPanel __instance, ref EFT.UI.ZombieEventLocationInfectionInfo ____infectionInfo) { }
    }

    public partial class EnablePrestigeTabPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void Postfix(EFT.UI.InventoryScreen.CG_ShowWithTab __instance) { }
    }

    public partial class FixAirdropCrashPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void Prefix() { }
    }

    public partial class FixAirdropFlareDisposePatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void Prefix(EFT.Airdrop.ProjectilesCollector __instance) { }
    }

    public partial class FixBossesHavingNoFollowersOnMediumAiAmount : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(LocalGame __instance, EFT.WavesSettings wavesSettings, ref BossLocationSpawn[] bossLocationSpawn) { }
    }

    public partial class FixKeylessDoorsPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
    }

    public partial class FixPmcSpawnParamsNullErrorPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(EFT.BotOwner bot) { }
    }

    public partial class FixPrecipitationAmbientBlenderNullRefPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(Audio.AmbientSubsystem.IAudioCrossfader ____crossfader, ref int ____lastClipHash, Audio.AmbientSubsystem.PrecipitationAmbientBlender __instance) { throw null; }
    }

    public partial class FixScavWarNullErrorWithMarkOfUnknownPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(BotsGroupMarkOfUnknown __instance) { throw null; }
    }

    public partial class KhorovodDisposeFix : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(EFT.RunddansController __instance) { }
    }

    public partial class LocaleManagerRaceConditionFixPatch : Reflection.Patching.ModulePatch
    {
        public static void AddCharacters(System.Collections.Generic.Dictionary<string, string> fontDictionary, TMPro.TMP_FontAsset mainFallBack) { }
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchTranspiler]
        public static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> PatchTranspile(System.Reflection.Emit.ILGenerator generator, System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions) { throw null; }
    }

    public partial class MatchStartServerLocationPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchTranspiler]
        public static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> PatchTranspile(System.Reflection.Emit.ILGenerator generator, System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions) { throw null; }
    }

    public partial class MemoryCollectionPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(EFT.UI.Screens.EEftScreenType eftScreenType) { }
    }

    public partial class MergeScavPmcQuestsOnInventoryLoadPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPreFix(ref System.Collections.Generic.IEnumerable<EFT.Quests.QuestDataClass> quests) { }
    }

    public partial class PreventClientModsPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix() { }
    }

    public partial class RedirectClientImageRequestsPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        public static System.Threading.Tasks.Task<UnityEngine.Texture2D> GetTexture0(string path) { throw null; }
        public static System.Threading.Tasks.Task<UnityEngine.Texture2D> GetTexture1(string path, string localPath) { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(string baseUrl, string url, ref System.Threading.Tasks.Task<UnityEngine.Texture2D> __result) { throw null; }
    }

    public partial class SaveRegistryToSptFolderPatches
    {
        public void Enable() { }
        public void Init() { }
        public partial class PatchPlayerPrefsDeleteAll : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }

        public partial class PatchPlayerPrefsDeleteKey : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }

        public partial class PatchPlayerPrefsGetFloat : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }

        public partial class PatchPlayerPrefsGetInt : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }

        public partial class PatchPlayerPrefsGetString : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }

        public partial class PatchPlayerPrefsHasKey : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }

        public partial class PatchPlayerPrefsSave : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }

        public partial class PatchPlayerPrefsSetFloat : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }

        public partial class PatchPlayerPrefsSetInt : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }

        public partial class PatchPlayerPrefsSetString : Reflection.Patching.ModulePatch
        {
            protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        }
    }
    public partial class SaveSettingsToSptFolderPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix() { }
    }

    public partial class SendFleaListingTaxAmountToServerPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(ref EFT.InventoryLogic.Item ____selectedItem, ref EFT.UI.RagfairNewOfferContext ____offerContext, ref double ____requirementsCost, ref bool ____sellInOnePiece) { }
    }

    public partial class SetPreRaidSettingsScreenDefaultsPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(EFT.UI.Matchmaker.MatchmakerOfflineRaidScreen __instance, EFT.UI.DefaultUIButton ____changeSettingsButton, EFT.UI.UiElementBlocker ____onlineBlocker) { }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(EFT.UI.Matchmaker.MatchmakerOfflineRaidScreen.OfflineRaidScreenController controller, EFT.UI.UpdatableToggle ____offlineModeToggle) { }
    }

    public partial class SpawnPointAIPlayerBotLimitPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref bool __result, BotCreationData creationData, UnityEngine.Vector3 ___Position) { throw null; }
    }

    public partial class SpawnPointNearestPlayerAIPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(ref EFT.Player __result, UnityEngine.Vector3 ___Position) { throw null; }
    }

    public partial class VersionLabelPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(object __result) { }
    }
}

namespace SPT.Custom.Utils
{
    public static partial class BundleCrcCache
    {
        public static void Load() { }
        public static void Save() { }
        public static bool TryGet(string key, out Models.CrcCacheEntry entry) { throw null; }
        public static void Update(string key, long size, uint crc) { }
    }
    public static partial class BundleManager
    {
        public static readonly System.Collections.Concurrent.ConcurrentDictionary<string, Models.BundleItem> Bundles;
        public static System.Threading.Tasks.Task DownloadBundle(Models.BundleItem bundle, System.Action<Common.Http.DownloadProgress> progressCallback) { throw null; }
        public static System.Threading.Tasks.Task DownloadManifest() { throw null; }
        public static string GetBundleFilePath(Models.BundleItem bundle) { throw null; }
        public static string GetBundlePath(Models.BundleItem bundle) { throw null; }
        public static System.Threading.Tasks.Task<bool> ShouldAcquire(Models.BundleItem bundle) { throw null; }
    }
    public static partial class Crc32
    {
        public static uint HashToUInt32(System.ReadOnlySpan<byte> source) { throw null; }
        public static uint Update(uint crc, System.ReadOnlySpan<byte> source) { throw null; }
    }
    public static partial class DifficultyManager
    {
        public static System.Collections.Generic.Dictionary<string, Models.DifficultyInfo> Difficulties { get { throw null; } }

        public static string Get(BotDifficulty botDifficulty, EFT.WildSpawnType role) { throw null; }
        public static void Update() { }
    }
    public partial class MenuNotificationManager : UnityEngine.MonoBehaviour
    {
        public static string CommitHash;
        public static string[] DisallowedPlugins;
        public static string SptVersion;
        public void Start() { }
        public void Update() { }
    }

    public partial class MessageBoxHelper
    {
        public static System.IntPtr GetWindowHandle() { throw null; }
        public static MessageBoxResult Show(string text, string caption, MessageBoxType type = MessageBoxType.DEFAULT) { throw null; }
        public enum MessageBoxResult
        {
            ERROR = -1,
            OK = 1,
            CANCEL = 2,
            ABORT = 3,
            RETRY = 4,
            IGNORE = 5,
            YES = 6,
            NO = 7,
            TRY_AGAIN = 10
        }

        public enum MessageBoxType : uint
        {
            RETRYCANCEL = 5U,
            DEFAULT = 16U,
            ABORTRETRYIGNORE = 18U,
            CANCELTRYCONTINUE = 54U,
            OK = 64U,
            OKCANCEL = 65U,
            YESNOCANCEL = 67U,
            YESNO = 68U,
            HELP = 16448U
        }
    }
}