//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPT.Debugging
{
    [BepInEx.BepInPlugin("com.SPT.debugging", "SPT.Debugging", "4.1.2")]
    public partial class SPTDebuggingPlugin : BepInEx.BaseUnityPlugin
    {
        public static Custom.Models.LoggingLevelResponse logLevel;
        public void Awake() { }
        public void Start() { }
    }
}

namespace SPT.Debugging.Commands
{
    public partial class DebugCommands
    {
        [ConsoleCommand("botmon", "", null, "botmon 0 - off; botmon 1 - on", new[] { })]
        public static void Botmon(int enabled) { }
        [ConsoleCommand("debug_extract", "", null, "keys: Survived, Killed, Runner, MissingInAction, Transit", new[] { })]
        public static void DebugExtract(EFT.ExitStatus status) { }
    }
}

namespace SPT.Debugging.Patches
{
    public partial class CoordinatesPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        public static UnityEngine.Vector3 LookingRaycast(EFT.Player player) { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPrefix(BaseLocalGame<EFT.EftGamePlayerOwner> __instance) { }
    }

    public partial class DataHandlerDebugPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPrefix(ref string __result) { }
    }

    public partial class DumpyLibPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(EFT.UI.MenuScreen __instance) { }
    }

    public partial class EndRaidDebug : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPreFix(TraderCard __instance, ref EFT.Profile.TraderInfo ____trader) { throw null; }
    }

    public partial class ExfilDumper : Reflection.Patching.ModulePatch
    {
        public static string DumpFolder;
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPreFix(JsonType.BackendExitTriggerSettings[] settings) { }
        public partial class SPTExfilData
        {
            public float Chance;
            public float ChancePVE;
            public int Count;
            public int CountPVE;
            public string EntryPoints;
            public bool EventAvailable;
            public float ExfiltrationTime;
            public float ExfiltrationTimePVE;
            public EFT.Interactive.EExfiltrationType ExfiltrationType;
            public string Id;
            public float MaxTime;
            public float MaxTimePVE;
            public float MinTime;
            public float MinTimePVE;
            public string Name;
            public EFT.Interactive.ERequirementState PassageRequirement;
            public int PlayersCount;
            public int PlayersCountPVE;
            public EFT.InventoryLogic.EquipmentSlot RequiredSlot;
            public string RequirementTip;
            public string Side;
            public SPTExfilData(EFT.Interactive.ExfiltrationPoint point, JsonType.BackendExitTriggerSettings settings) { }
        }
    }

    public partial class LoggerClassLogPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix(string nlogFormat, string unityFormat, NLog.LogLevel logLevel, object[] args) { }
    }

    public partial class PMCBotSpawnLocationPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPrefix]
        public static bool PatchPrefix(EFT.BotSpawner __instance, BotCreationData data) { throw null; }
    }

    public partial class ReloadClientPatch : Reflection.Patching.ModulePatch
    {
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        [Reflection.Patching.PatchPostfix]
        public static void PatchPostfix() { }
        [ConsoleCommand("reload", "", null, "Reloads currently loaded profile.\nOnly use while in Main Menu\nRunning command while in hideout will cause graphical glitches and NRE to do with Nightvision. Pretty sure wont cause anything bad\nMay Cause Unexpected Behaviors inraid", new[] { })]
        public static void Reload() { }
    }

    public partial class SPTContainer
    {
        public string groupId;
    }
    public partial class SPTContainersData
    {
        public System.Collections.Generic.Dictionary<string, SPTContainer> containers;
        public System.Collections.Generic.Dictionary<string, SPTContainersGroup> containersGroups;
    }
    public partial class SPTContainersGroup
    {
        public int maxContainers;
        public int minContainers;
    }
    public partial class SptSpawnHelper
    {
        public void PrintSpawnPoints() { }
        public EFT.Game.Spawning.ISpawnPoint SelectSpawnPoint() { throw null; }
        public System.Collections.Generic.List<EFT.Game.Spawning.ISpawnPoint> SelectSpawnPoints(int count) { throw null; }
    }
    public partial class StaticLootDumper : Reflection.Patching.ModulePatch
    {
        public static string DumpFolder;
        protected override System.Reflection.MethodBase GetTargetMethod() { throw null; }
        public static void InitDirectory() { }
        [Reflection.Patching.PatchPrefix]
        public static void PatchPreFix() { }
    }
}

namespace SPT.Debugging.Scripts
{
    public partial class BotmonitorScript : UnityEngine.MonoBehaviour
    {
        public UnityEngine.GUIStyle TextStyle;
        public void Awake() { }
        public void DestorySelf() { }
        public BotRoleAndDiffClass GetBotRoleAndDiffClass(EFT.ProfileInfo info) { throw null; }
        public void OnBotCreatedHandler(EFT.BotOwner owner) { }
        public void OnBotRemovedHandler(EFT.BotOwner owner) { }
        public void OnGUI() { }
    }

    public partial class BotRoleAndDiffClass
    {
        public BotRoleAndDiffClass(string role = "", string difficulty = "") { }
        public string Difficulty { get { throw null; } set { } }
        public string Role { get { throw null; } set { } }
    }
    public partial class DumpylibScript : UnityEngine.MonoBehaviour
    {
        public EFT.ProfileDescriptor _completeProfile;
        public EFT.SessionResult _endRaidClass;
        public EFT.LocalRaidSettings _localRaidSettings;
        public JsonType.LocationSettings _locationSettings;
        public System.Collections.Generic.List<JsonType.LocationSettings.Location> _locationSettingsDict;
        public System.Reflection.FieldInfo[] _locationSettingsFields;
        public System.Reflection.FieldInfo _mainMenuController;
        public UnparsedData _parsedDataProfile;
        public EFT.RaidSettings _raidSettings;
        public System.Reflection.FieldInfo _raidSettingsField;
        public System.Type _raidSettingsType;
        public EFT.EftClientBackendSession _session;
        public EFT.TarkovApplication _tarkovApplication;
        public EFT.CountTypeBotWave _wavesSettings;
        public JsonType.WeatherResponse _weather;
        protected static BepInEx.Logging.ManualLogSource Logger { get { throw null; } }
    }
}