//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SPT.Reflection
{
    public static partial class MyPluginInfo
    {
        public const string PLUGIN_GUID = "spt-reflection";
        public const string PLUGIN_NAME = "spt-reflection";
        public const string PLUGIN_VERSION = "1.0.0";
    }
}

namespace SPT.Reflection.CodeWrapper
{
    public partial class Code
    {
        public Code(System.Reflection.Emit.OpCode opCode, object operandTarget) { }
        public Code(System.Reflection.Emit.OpCode opCode, System.Type callerType, object operandTarget, System.Type[] parameters = null) { }
        public Code(System.Reflection.Emit.OpCode opCode, System.Type callerType) { }
        public Code(System.Reflection.Emit.OpCode opCode) { }
        public System.Type CallerType { get { throw null; } }
        public bool HasOperand { get { throw null; } }
        public System.Reflection.Emit.OpCode OpCode { get { throw null; } }
        public object OperandTarget { get { throw null; } }
        public System.Type[] Parameters { get { throw null; } }

        public virtual System.Reflection.Emit.Label? GetLabel() { throw null; }
    }
    public partial class CodeGenerator
    {
        public static System.Collections.Generic.List<HarmonyLib.CodeInstruction> GenerateInstructions(System.Collections.Generic.List<Code> codes) { throw null; }
    }
    public partial class CodeWithLabel : Code
    {
        public CodeWithLabel(System.Reflection.Emit.OpCode opCode, System.Reflection.Emit.Label label, object operandTarget) : base(default) { }
        public CodeWithLabel(System.Reflection.Emit.OpCode opCode, System.Reflection.Emit.Label label, System.Type callerType, object operandTarget, System.Type[] parameters = null) : base(default) { }
        public CodeWithLabel(System.Reflection.Emit.OpCode opCode, System.Reflection.Emit.Label label, System.Type callerType) : base(default) { }
        public CodeWithLabel(System.Reflection.Emit.OpCode opCode, System.Reflection.Emit.Label label) : base(default) { }
        public System.Reflection.Emit.Label Label { get { throw null; } }

        public override System.Reflection.Emit.Label? GetLabel() { throw null; }
    }
}

namespace SPT.Reflection.Patching
{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public partial class DebugPatchAttribute : System.Attribute
    {
    }

    [System.AttributeUsage(System.AttributeTargets.Class)]
    public partial class IgnoreAutoPatchAttribute : System.Attribute
    {
    }

    public static partial class ModPatchCache
    {
        public static System.Collections.Generic.List<string> GetActivePatchedMethodNames() { throw null; }
        public static System.Collections.Generic.IReadOnlyList<ModulePatch> GetActivePatches() { throw null; }
    }
    public abstract partial class ModulePatch
    {
        protected ModulePatch() { }
        protected ModulePatch(string name = null) { }
        public string HarmonyId { get { throw null; } }
        public bool IsActive { get { throw null; } }
        public bool IsManaged { get { throw null; } }
        protected static BepInEx.Logging.ManualLogSource Logger { get { throw null; } }
        public System.Reflection.MethodBase? TargetMethod { get { throw null; } }

        public void Disable() { }
        public void Enable() { }
        protected abstract System.Reflection.MethodBase GetTargetMethod();
    }
    public partial class PatchException : System.Exception
    {
        public PatchException(string message, System.Exception innerException) { }
        public PatchException(string message) { }
    }

    [JetBrains.Annotations.MeansImplicitUse]
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchFinalizerAttribute : System.Attribute
    {
    }

    [JetBrains.Annotations.MeansImplicitUse]
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchILManipulatorAttribute : System.Attribute
    {
    }

    public partial class PatchManager
    {
        public PatchManager(BepInEx.BaseUnityPlugin unityPlugin, bool autoPatch) { }
        public PatchManager(BepInEx.BaseUnityPlugin unityPlugin) { }
        public PatchManager(string guid, string pluginName, bool autoPatch) { }
        public PatchManager(string guid, string pluginName) { }
        public void AddPatch(ModulePatch patch) { }
        public void AddPatches(System.Collections.Generic.List<ModulePatch> patchList) { }
        public void DisablePatch(ModulePatch patch) { }
        public void DisablePatches() { }
        public void EnablePatch(ModulePatch patch) { }
        public void EnablePatches() { }
    }
    [JetBrains.Annotations.MeansImplicitUse]
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchPostfixAttribute : System.Attribute
    {
    }

    [JetBrains.Annotations.MeansImplicitUse]
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchPrefixAttribute : System.Attribute
    {
    }

    [JetBrains.Annotations.MeansImplicitUse]
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public partial class PatchTranspilerAttribute : System.Attribute
    {
    }
}

namespace SPT.Reflection.Utils
{
    public static partial class ClientAppUtils
    {
        public static EFT.ClientApplication<EFT.IEftSession> GetClientApp() { throw null; }
        public static EFT.TarkovApplication GetMainApp() { throw null; }
    }
    public static partial class PatchConstants
    {
        public static System.Type BackendProfileInterfaceType { get { throw null; } }
        public static EFT.IEftSession BackEndSession { get { throw null; } }
        public static System.Type BackendSessionInterfaceType { get { throw null; } }
        public static System.Type[] EftTypes { get { throw null; } }
        public static System.Type ExfilPointManagerType { get { throw null; } }
        public static System.Type[] FilesCheckerTypes { get { throw null; } }
        public static System.Type LocalGameType { get { throw null; } }
        public static System.Reflection.BindingFlags PrivateFlags { get { throw null; } }
        public static System.Reflection.BindingFlags PublicDeclaredFlags { get { throw null; } }
        public static System.Reflection.BindingFlags PublicFlags { get { throw null; } }
        public static System.Type SessionInterfaceType { get { throw null; } }

        public static T SingleCustom<T>(this System.Collections.Generic.IEnumerable<T> types, System.Func<T, bool> predicate) where T : System.Reflection.MemberInfo { throw null; }
    }
}